name: "SAST"

on:
  push:
    branches: [ "main" ]

jobs:
  CodeQL:
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'cpp'

    # - name: Autobuild
    #   uses: github/codeql-action/autobuild@v3

    - name: Custom build
      run: |
        g++ -g -std=c++17 -o fileserver main/main.cpp -lssl -lcrypto

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
